### ISSUE TITLE
MywaJS

### ISSUE THREAD

**Issue by amiruldev20** [amiruldev20/mywajs#1]
menerima segala saran dan request

**Comment by pakhermawan23** [comment]
Bisa request multi client no wa. Dan ketika broadcast pesan bisa terdistribusi secara acak dan merata kesemua client. Makasih sebelumnya

**Comment by amiruldev20** [comment]
baik mulai senin diusahakan

**Comment by rizkisquadpants** [comment]
Masih Beta kah Mas ? @amiruldev20

**Comment by amiruldev20** [comment]
iya mas. menerima segala masukan dan request fitur

**Comment by amiruldev20** [comment]
@pakhermawan23 multi client (multi sesi?) sudah bisa

**Comment by pakhermawan23** [comment]
> @pakhermawan23 multi client (multi sesi?) sudah bisa

Mantap... go to TKP
