### ISSUE TITLE
Error in m.reply

### ISSUE THREAD

**Issue by DEFF-Y** [amiruldev20/mywajs#12]
TypeError: data.id.id.substring is not a function
0|deff  |     at Message._patch (file:///waweb/node_modules/mywajs/src/func/Message.js:92:75)
0|deff  |     at new Message (file:///waweb/node_modules/mywajs/src/func/Message.js:19:24)
0|deff  |     at Client.sendMessage (file:///waweb/node_modules/mywajs/src/Client.js:1029:32)
0|deff  |     at runNextTicks (node:internal/process/task_queues:60:5)
0|deff  |     at process.processImmediate (node:internal/timers:449:9)

**Comment by amiruldev20** [comment]
sudah coba npm update?
