### ISSUE TITLE
page.waitForSelector: Timeout 10000ms exceeded.

### ISSUE THREAD

**Issue by matthelosh** [amiruldev20/mywajs#17]
Halo, I got this error. What does it mean?
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.waitForSelector: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('[data-testid="intro-md-beta-logo-dark"], [data-testid="intro-md-beta-logo-light"], [data-asset-intro-image-light="true"], [data-asset-intro-image-dark="true"]') to be visible
============================================================
    at Promise.race.page.waitForSelector.timeout (file:///D:/Projects/mywaapi/node_modules/mywajs/src/Client.js:329:22)
    at Client.initialize (file:///D:/Projects/mywaapi/node_modules/mywajs/src/Client.js:328:13) {
  name: 'TimeoutError'
}

**Comment by renzhxr** [comment]
what are you wearing? localAuth?

**Comment by matthelosh** [comment]
Yes, I am using localAuth

**Comment by renzhxr** [comment]
there is information in the community, you can read it

**Comment by matthelosh** [comment]
Oke, thank you

**Comment by amiruldev20** [comment]
hello, thanks for reporting. for now I'm fixing mywajs, there are several updates from the whatsapp web

**Comment by amiruldev20** [comment]
done.update use github version
