### ISSUE TITLE
Please doc

### ISSUE THREAD

**Issue by amosayomide05** [amiruldev20/mywajs#2]
There is no documentation on how to use the extra features

**Comment by amosayomide05** [comment]
https://amiruldev20.github.io/mywajs/client.html#


This is not complete

**Comment by amosayomide05** [comment]
> This lib is under construction, please be patient. the full version will be released soon

Ok thanks

**Comment by amiruldev20** [comment]
join group discussions for notif update

**Comment by amiruldev20** [comment]
https://mywajs.amirull.dev
