### ISSUE TITLE
Error [ERR_REQUIRE_ESM] bwang

### ISSUE THREAD

**Issue by officialdittaz** [amiruldev20/mywajs#3]
/home/runner/Fearless-wa-webjs/node_modules/wwebjs/src/util/Util.js:3
const fileType = require("file-type");
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/Fearless-wa-webjs/node_modules/file-type/index.js from /home/runner/Fearless-wa-webjs/node_modules/wwebjs/src/util/Util.js not supported.
Instead change the require of index.js in /home/runner/Fearless-wa-webjs/node_modules/wwebjs/src/util/Util.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/Fearless-wa-webjs/node_modules/wwebjs/src/util/Util.js:3:18)
    at Object.<anonymous> (/home/runner/Fearless-wa-webjs/node_modules/wwebjs/src/Client.js:15:14)
    at Object.<anonymous> (/home/runner/Fearless-wa-webjs/node_modules/wwebjs/index.js:16:13) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by officialdittaz** [comment]
make file-type versi last

**Comment by amiruldev20** [comment]
oke next update

**Comment by amiruldev20** [comment]
importnya gini aja
import pkg from 'file-type'
const { fromBuffer } = pkg

nanti tinggal fromBuffer manggilnya. make filetype bawaan. soalnya problem kl diupdate latest
